# Generated by Django 3.1.3 on 2020-11-30 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('available', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=200)),
                ('petrol', models.CharField(choices=[('diesel', 'Diesel'), ('essance', 'Essence ')], max_length=10)),
                ('KM', models.IntegerField()),
                ('picture', models.ImageField(blank=True, upload_to='upload')),
            ],
            options={
                'verbose_name': 'voiture',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=100)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'prospect',
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contacted', models.BooleanField(default=False)),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.car')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.contact')),
            ],
            options={
                'verbose_name': 'réservation',
            },
        ),
    ]
