# Generated by Django 3.1.3 on 2020-12-01 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='picture',
            field=models.ImageField(upload_to='upload'),
        ),
    ]
