# Generated by Django 3.1.3 on 2020-12-01 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20201201_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='KM',
        ),
        migrations.RemoveField(
            model_name='car',
            name='petrol',
        ),
        migrations.RemoveField(
            model_name='car',
            name='picture',
        ),
    ]
