# Generated by Django 3.1.3 on 2020-12-01 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20201201_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='KM',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='petrol',
            field=models.CharField(choices=[('diesel', 'Diesel'), ('essance', 'Essence ')], default='diesel', max_length=10),
        ),
        migrations.AddField(
            model_name='car',
            name='picture',
            field=models.ImageField(null=True, upload_to='upload'),
        ),
        migrations.AlterField(
            model_name='car',
            name='reference',
            field=models.IntegerField(),
        ),
    ]
