# Generated by Django 3.1.3 on 2020-12-01 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20201201_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='picture',
            field=models.ImageField(blank=True, default='unknown.jpg', upload_to='upload'),
        ),
    ]
